//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarrenHills01
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaTarea
    {
        public long IdHistoriaTarea { get; set; }
        public long IdTarea { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime Fecha_Finalizacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual TareaSemanal TareaSemanal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
