//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarrenHills01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WarrenHills01Entities : DbContext
    {
        public WarrenHills01Entities()
            : base("name=WarrenHills01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dashboard> Dashboard { get; set; }
        public virtual DbSet<Gasto_Mensual> Gasto_Mensual { get; set; }
        public virtual DbSet<HistoriaTarea> HistoriaTarea { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SysDiagrams> SysDiagrams { get; set; }
        public virtual DbSet<TareaSemanal> TareaSemanal { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<ConsultaHistoriaTareas_Result> ConsultaHistoriaTareas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultaHistoriaTareas_Result>("ConsultaHistoriaTareas");
        }
    
        public virtual ObjectResult<ConsultaTareasUsuarios_Result> ConsultaTareasUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultaTareasUsuarios_Result>("ConsultaTareasUsuarios");
        }
    
        public virtual int InsertaDash(Nullable<int> iDUSUARIO, Nullable<int> iDTAREA, string dIASEMANA)
        {
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var iDTAREAParameter = iDTAREA.HasValue ?
                new ObjectParameter("IDTAREA", iDTAREA) :
                new ObjectParameter("IDTAREA", typeof(int));
    
            var dIASEMANAParameter = dIASEMANA != null ?
                new ObjectParameter("DIASEMANA", dIASEMANA) :
                new ObjectParameter("DIASEMANA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaDash", iDUSUARIOParameter, iDTAREAParameter, dIASEMANAParameter);
        }
    
        public virtual int InsertarHistorial(Nullable<int> iDT, Nullable<int> iDUSUARIO, Nullable<System.DateTime> fECHA, string cOMENTARIOS)
        {
            var iDTParameter = iDT.HasValue ?
                new ObjectParameter("IDT", iDT) :
                new ObjectParameter("IDT", typeof(int));
    
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var cOMENTARIOSParameter = cOMENTARIOS != null ?
                new ObjectParameter("COMENTARIOS", cOMENTARIOS) :
                new ObjectParameter("COMENTARIOS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarHistorial", iDTParameter, iDUSUARIOParameter, fECHAParameter, cOMENTARIOSParameter);
        }
    
        public virtual int InsertaUsuario(string nOMBRE, string aPELLIDO, string cORREOELECTRONICO, string cLAVE, Nullable<int> iDROLL)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var cORREOELECTRONICOParameter = cORREOELECTRONICO != null ?
                new ObjectParameter("CORREOELECTRONICO", cORREOELECTRONICO) :
                new ObjectParameter("CORREOELECTRONICO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var iDROLLParameter = iDROLL.HasValue ?
                new ObjectParameter("IDROLL", iDROLL) :
                new ObjectParameter("IDROLL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaUsuario", nOMBREParameter, aPELLIDOParameter, cORREOELECTRONICOParameter, cLAVEParameter, iDROLLParameter);
        }
    
        public virtual ObjectResult<TareasUsuarioUnico_Result> TareasUsuarioUnico(Nullable<int> iDUSUARIO)
        {
            var iDUSUARIOParameter = iDUSUARIO.HasValue ?
                new ObjectParameter("IDUSUARIO", iDUSUARIO) :
                new ObjectParameter("IDUSUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TareasUsuarioUnico_Result>("TareasUsuarioUnico", iDUSUARIOParameter);
        }
    }
}
